return {
	{
		GiftNumber = 1,
		Time = 5 * 60, -- 5 minutes
		Reward = 250,
	},
	{
		GiftNumber = 2,
		Time = 10 * 60, -- 10 minutes
		Reward = 500,
	},
	{
		GiftNumber = 3,
		Time = 15 * 60, -- 15 minutes
		Reward = 750,
		Gear = "BloxyCola",
	},
	{
		GiftNumber = 4,
		Time = 20 * 60, -- 20 minutes
		Reward = 1000,
	},
	{
		GiftNumber = 5,
		Time = 30 * 60, -- 30 minutes
		Reward = 1500,
	},
	{
		GiftNumber = 6,
		Time = 40 * 60, -- 40 minutes
		Reward = 2000,
		Gear = "Cheezburger",
	},
	{
		GiftNumber = 7,
		Time = 50 * 60, -- 50 minutes
		Reward = 2500,
	},
	{
		GiftNumber = 8,
		Time = 60 * 60, -- 1 hour
		Reward = 3500,
	},
	{
		GiftNumber = 9,
		Time = 75 * 60, -- 1 hour 15 minutes
		Reward = 4500,
		Gear = "Pizza",
	},
	{
		GiftNumber = 10,
		Time = 90 * 60, -- 1 hour 30 minutes
		Reward = 6000,
	},
	{
		GiftNumber = 11,
		Time = 110 * 60, -- 1 hour 50 minutes
		Reward = 8000,
	},
	{
		GiftNumber = 12,
		Time = 120 * 60, -- 2 hours
		Reward = 10000,
		Gear = "Pizza",
		Item = "GravityCoil",
	},
}
