return {
	UpdatePlayerData = "Event",
	GoBackStage = "Function",
	GoForwardStage = "Function",
	UseSkip = "Function",
	UseFinish = "Function",
	ShowFinishPart = "Event",
	HideFinishPart = "Event",
	UpdateCamera = "Event",

	BuyGearWithCash = "Function",
	GearEffectStarted = "Event",
	GearEffectEnded = "Event",

	GetPlaytimeData = "Function",
	ClaimGift = "Function",
	PlaytimeUpdated = "Event",

	BuyUpgrade = "Function",

	GetDailyRewardsData = "Function",
	ClaimDailyReward = "Function",
	DailyRewardAvailable = "Event",
	DailyRewardsClosed = "Event",

	DiamondSlapCountdown = "Event",
	DiamondSlapUnlocked = "Event",
	DiamondSlapCollected = "Event",

	RobuxPurchaseCompleted = "Event",

	SaveSettings = "Function",
}
