--[[
Made By Wheez
--]]
return {
	--[[
	Time In Seconds
	--]]
	{
		GiftNumber = 1,
		Time = (5 * 60),
		Reward = {
			["Currency"] = "Coins",
			["Amount"] = 250,
		},
	},
	{
		GiftNumber = 2,
		Time = (12 * 60),
		Reward = {
			["Currency"] = "Coins",
			["Amount"] = 550,
		},
	},
	{
		GiftNumber = 3,
		Time = (20 * 60),
		Reward = {
			["Currency"] = "Coins",
			["Amount"] = 1050,
		},
	},
	{
		GiftNumber = 4,
		Time = (28 * 60),
		Reward = {
			["Currency"] = "Coins",
			["Amount"] = 1450,
		},
	},
	{
		GiftNumber = 5,
		Time = (35 * 60),
		Reward = {
			["Currency"] = "Coins",
			["Amount"] = 2050,
		},
	},
	{
		GiftNumber = 6,
		Time = (45 * 60),
		Reward = {
			["Currency"] = "Coins",
			["Amount"] = 3250,
		},
	},
	{
		GiftNumber = 7,
		Time = (50 * 60),
		Reward = {
			["Currency"] = "Coins",
			["Amount"] = 3950,
		},
	},
	{
		GiftNumber = 8,
		Time = (75 * 60),
		Reward = {
			["Currency"] = "Coins",
			["Amount"] = 4650,
		},
	},
	{
		GiftNumber = 9,
		Time = (100 * 60),
		Reward = {
			["Currency"] = "Coins",
			["Amount"] = 7050,
		},
	},
}
